/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyBackRouteImport } from './routes/buy-back'
import { Route as ComparatieRouteImport } from './routes/comparatie'
import { Route as InAfaraScopuluiRouteImport } from './routes/in-afara-scopului'
import { Route as SucursaleRouteImport } from './routes/sucursale'
import { Route as VerificareMasiniRulateRouteImport } from './routes/verificare-masini-rulate'
import { Route as AutoturismeIndexRouteImport } from './routes/autoturisme.index'
import { Route as AutoturismeSlugRouteImport } from './routes/autoturisme.$slug'
import { Route as RezervareSlugRouteImport } from './routes/rezervare.$slug'
import { Route as ServiceDosarDauneRouteImport } from './routes/service.dosar-daune'
import { Route as ServiceProgramareRouteImport } from './routes/service.programare'
import { Route as ServiceTarifeRouteImport } from './routes/service.tarife'
import { Route as ServiceUrgentRouteImport } from './routes/service.urgent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyBackRoute = BuyBackRouteImport.update({
  id: '/buy-back',
  path: '/buy-back',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatieRoute = ComparatieRouteImport.update({
  id: '/comparatie',
  path: '/comparatie',
  getParentRoute: () => rootRouteImport,
} as any)
const InAfaraScopuluiRoute = InAfaraScopuluiRouteImport.update({
  id: '/in-afara-scopului',
  path: '/in-afara-scopului',
  getParentRoute: () => rootRouteImport,
} as any)
const SucursaleRoute = SucursaleRouteImport.update({
  id: '/sucursale',
  path: '/sucursale',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificareMasiniRulateRoute = VerificareMasiniRulateRouteImport.update({
  id: '/verificare-masini-rulate',
  path: '/verificare-masini-rulate',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoturismeIndexRoute = AutoturismeIndexRouteImport.update({
  id: '/autoturisme/',
  path: '/autoturisme/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoturismeSlugRoute = AutoturismeSlugRouteImport.update({
  id: '/autoturisme/$slug',
  path: '/autoturisme/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RezervareSlugRoute = RezervareSlugRouteImport.update({
  id: '/rezervare/$slug',
  path: '/rezervare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceDosarDauneRoute = ServiceDosarDauneRouteImport.update({
  id: '/service/dosar-daune',
  path: '/service/dosar-daune',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceProgramareRoute = ServiceProgramareRouteImport.update({
  id: '/service/programare',
  path: '/service/programare',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceTarifeRoute = ServiceTarifeRouteImport.update({
  id: '/service/tarife',
  path: '/service/tarife',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceUrgentRoute = ServiceUrgentRouteImport.update({
  id: '/service/urgent',
  path: '/service/urgent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy-back': typeof BuyBackRoute
  '/comparatie': typeof ComparatieRoute
  '/in-afara-scopului': typeof InAfaraScopuluiRoute
  '/sucursale': typeof SucursaleRoute
  '/verificare-masini-rulate': typeof VerificareMasiniRulateRoute
  '/autoturisme/$slug': typeof AutoturismeSlugRoute
  '/rezervare/$slug': typeof RezervareSlugRoute
  '/service/dosar-daune': typeof ServiceDosarDauneRoute
  '/service/programare': typeof ServiceProgramareRoute
  '/service/tarife': typeof ServiceTarifeRoute
  '/service/urgent': typeof ServiceUrgentRoute
  '/autoturisme/': typeof AutoturismeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy-back': typeof BuyBackRoute
  '/comparatie': typeof ComparatieRoute
  '/in-afara-scopului': typeof InAfaraScopuluiRoute
  '/sucursale': typeof SucursaleRoute
  '/verificare-masini-rulate': typeof VerificareMasiniRulateRoute
  '/autoturisme/$slug': typeof AutoturismeSlugRoute
  '/rezervare/$slug': typeof RezervareSlugRoute
  '/service/dosar-daune': typeof ServiceDosarDauneRoute
  '/service/programare': typeof ServiceProgramareRoute
  '/service/tarife': typeof ServiceTarifeRoute
  '/service/urgent': typeof ServiceUrgentRoute
  '/autoturisme': typeof AutoturismeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy-back': typeof BuyBackRoute
  '/comparatie': typeof ComparatieRoute
  '/in-afara-scopului': typeof InAfaraScopuluiRoute
  '/sucursale': typeof SucursaleRoute
  '/verificare-masini-rulate': typeof VerificareMasiniRulateRoute
  '/autoturisme/$slug': typeof AutoturismeSlugRoute
  '/rezervare/$slug': typeof RezervareSlugRoute
  '/service/dosar-daune': typeof ServiceDosarDauneRoute
  '/service/programare': typeof ServiceProgramareRoute
  '/service/tarife': typeof ServiceTarifeRoute
  '/service/urgent': typeof ServiceUrgentRoute
  '/autoturisme/': typeof AutoturismeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy-back'
    | '/comparatie'
    | '/in-afara-scopului'
    | '/sucursale'
    | '/verificare-masini-rulate'
    | '/autoturisme/$slug'
    | '/rezervare/$slug'
    | '/service/dosar-daune'
    | '/service/programare'
    | '/service/tarife'
    | '/service/urgent'
    | '/autoturisme/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy-back'
    | '/comparatie'
    | '/in-afara-scopului'
    | '/sucursale'
    | '/verificare-masini-rulate'
    | '/autoturisme/$slug'
    | '/rezervare/$slug'
    | '/service/dosar-daune'
    | '/service/programare'
    | '/service/tarife'
    | '/service/urgent'
    | '/autoturisme'
  id:
    | '__root__'
    | '/'
    | '/buy-back'
    | '/comparatie'
    | '/in-afara-scopului'
    | '/sucursale'
    | '/verificare-masini-rulate'
    | '/autoturisme/$slug'
    | '/rezervare/$slug'
    | '/service/dosar-daune'
    | '/service/programare'
    | '/service/tarife'
    | '/service/urgent'
    | '/autoturisme/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyBackRoute: typeof BuyBackRoute
  ComparatieRoute: typeof ComparatieRoute
  InAfaraScopuluiRoute: typeof InAfaraScopuluiRoute
  SucursaleRoute: typeof SucursaleRoute
  VerificareMasiniRulateRoute: typeof VerificareMasiniRulateRoute
  AutoturismeSlugRoute: typeof AutoturismeSlugRoute
  RezervareSlugRoute: typeof RezervareSlugRoute
  ServiceDosarDauneRoute: typeof ServiceDosarDauneRoute
  ServiceProgramareRoute: typeof ServiceProgramareRoute
  ServiceTarifeRoute: typeof ServiceTarifeRoute
  ServiceUrgentRoute: typeof ServiceUrgentRoute
  AutoturismeIndexRoute: typeof AutoturismeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-back': {
      id: '/buy-back'
      path: '/buy-back'
      fullPath: '/buy-back'
      preLoaderRoute: typeof BuyBackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparatie': {
      id: '/comparatie'
      path: '/comparatie'
      fullPath: '/comparatie'
      preLoaderRoute: typeof ComparatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-afara-scopului': {
      id: '/in-afara-scopului'
      path: '/in-afara-scopului'
      fullPath: '/in-afara-scopului'
      preLoaderRoute: typeof InAfaraScopuluiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucursale': {
      id: '/sucursale'
      path: '/sucursale'
      fullPath: '/sucursale'
      preLoaderRoute: typeof SucursaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificare-masini-rulate': {
      id: '/verificare-masini-rulate'
      path: '/verificare-masini-rulate'
      fullPath: '/verificare-masini-rulate'
      preLoaderRoute: typeof VerificareMasiniRulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoturisme/': {
      id: '/autoturisme/'
      path: '/autoturisme'
      fullPath: '/autoturisme/'
      preLoaderRoute: typeof AutoturismeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoturisme/$slug': {
      id: '/autoturisme/$slug'
      path: '/autoturisme/$slug'
      fullPath: '/autoturisme/$slug'
      preLoaderRoute: typeof AutoturismeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezervare/$slug': {
      id: '/rezervare/$slug'
      path: '/rezervare/$slug'
      fullPath: '/rezervare/$slug'
      preLoaderRoute: typeof RezervareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/dosar-daune': {
      id: '/service/dosar-daune'
      path: '/service/dosar-daune'
      fullPath: '/service/dosar-daune'
      preLoaderRoute: typeof ServiceDosarDauneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/programare': {
      id: '/service/programare'
      path: '/service/programare'
      fullPath: '/service/programare'
      preLoaderRoute: typeof ServiceProgramareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/tarife': {
      id: '/service/tarife'
      path: '/service/tarife'
      fullPath: '/service/tarife'
      preLoaderRoute: typeof ServiceTarifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/urgent': {
      id: '/service/urgent'
      path: '/service/urgent'
      fullPath: '/service/urgent'
      preLoaderRoute: typeof ServiceUrgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyBackRoute: BuyBackRoute,
  ComparatieRoute: ComparatieRoute,
  InAfaraScopuluiRoute: InAfaraScopuluiRoute,
  SucursaleRoute: SucursaleRoute,
  VerificareMasiniRulateRoute: VerificareMasiniRulateRoute,
  AutoturismeSlugRoute: AutoturismeSlugRoute,
  RezervareSlugRoute: RezervareSlugRoute,
  ServiceDosarDauneRoute: ServiceDosarDauneRoute,
  ServiceProgramareRoute: ServiceProgramareRoute,
  ServiceTarifeRoute: ServiceTarifeRoute,
  ServiceUrgentRoute: ServiceUrgentRoute,
  AutoturismeIndexRoute: AutoturismeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
